name: fyp_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  go_router: ^14.8.1
  camera: ^0.11.1
  video_player: ^2.5.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.0.1
  google_sign_in: ^6.2.0
  cloud_firestore: ^5.0.1
  get: ^4.7.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/video/hand_video.mp4
    - assets/images/google.png
    - assets/images/AppLogo.jpeg



